# Compose to Kotlin Compatibility Map:
# https://d.android.com/jetpack/androidx/releases/compose-kotlin

[versions]
min-sdk = "21"
compile-sdk = "33"
target-sdk = "33"
build-tools = "33.0.0"
gradle = "7.3.1"
kotlin = "1.7.21"
kotlin-coroutines = "1.6.4"
kotlin-serialization = "1.4.1"
kotlin-compiler-extension = "1.4.0-alpha02"
detekt = "1.22.0"
spotless = "6.12.0"
google-services = "4.3.14"
play-services-ads = "21.3.0"
play-services-base = "18.1.0"
firebase-analytics = "21.2.0"
firebase-appdistribution = "3.1.1"
firebase-config = "21.2.0"
firebase-crashlytics-plugin = "2.9.2"
firebase-crashlytics = "18.3.2"
play-core = "1.8.1"
accompanist = "0.27.1"
compose-foundation = "1.3.1"
compose-runtime = "1.3.1"
compose-ui = "1.3.1"
compose-compiler = "1.3.2"
compose-material3 = "1.0.1"
material = "1.6.0"
material-compose-theme-adapter = "1.2.0"
appcompat = "1.6.0-rc01"
activity = "1.6.1"
core = "1.9.0"
core-splashscreen = "1.0.0"
constraintlayout = "1.0.1"
lifecycle = "2.6.0-alpha03"
hilt = "2.44.2"
hilt-navigation-compose = "1.0.0"
navigation = "2.5.3"
paging = "1.0.0-alpha17"
datastore = "1.0.0"
startup = "1.1.1"
coil = "2.2.2"
okhttp = "4.10.0"
retrofit = "2.9.0"
retrofit-converter-serialization = "0.8.0"
chucker = "3.5.2"
timber = "5.0.1"
javapoet = "1.13.0"
room = "2.4.3"

junit = "4.13.2"
test = "1.5.0"
test-ext = "1.1.4"
espresso-core = "3.5.0"

[libraries]
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "play-services-ads" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "play-services-base" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebase-analytics" }
firebase-config = { module = "com.google.firebase:firebase-config-ktx", version.ref = "firebase-config" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebase-crashlytics" }
play-core = { module = "com.google.android.play:core-ktx", version.ref = "play-core" }
accompanist-appcompat-theme = { module = "com.google.accompanist:accompanist-appcompat-theme", version.ref = "accompanist" }
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-insets-ui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose-foundation" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose-ui" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-compose-theme-adapter = { module = "com.google.android.material:compose-theme-adapter", version.ref = "material-compose-theme-adapter" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
core = { module = "androidx.core:core-ktx", version.ref = "core" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-converter-serialization" }
chucker-library = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-library-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }

junit = { module = "junit:junit", version.ref = "junit" }
test-rules = { module = "androidx.test:rules", version.ref = "test" }
test-runner = { module = "androidx.test:runner", version.ref = "test" }
test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "test-ext" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }

gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
kotlin-coroutines = [
    "kotlin-coroutines-android",
    "kotlin-coroutines-core"
]
accompanist = [
    "accompanist-appcompat-theme",
    "accompanist-drawablepainter",
    "accompanist-insets",
    "accompanist-insets-ui",
    "accompanist-navigation-animation",
    "accompanist-placeholder",
    "accompanist-placeholder-material",
    "accompanist-systemuicontroller"
]
appcompat = [
    "appcompat",
    "appcompat-resources"
]
compose = [
    "compose-compiler",
    "compose-foundation",
    "compose-foundation-layout",
    "compose-material3",
    "compose-runtime",
    "compose-ui",
    "compose-ui-tooling",
    "compose-ui-viewbinding"
]
datastore = [
    "datastore-core",
    "datastore-preferences",
    "datastore-preferences-core"
]
lifecycle = [
    "lifecycle-runtime-compose",
    "lifecycle-viewmodel-compose"
]
material = [
    "material",
    "material-compose-theme-adapter"
]

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebase-appdistribution" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }