# Compose to Kotlin Compatibility Map:
# https://d.android.com/jetpack/androidx/releases/compose-kotlin

[versions]
min-sdk = "21"
compile-sdk = "33"
target-sdk = "33"
build-tools = "33.0.0"
gradle = "7.3.1"
kotlin = "1.7.21"
kotlin-coroutines = "1.6.4"
kotlin-serialization = "1.4.0"
kotlin-compiler-extension = "1.4.0-alpha02"
detekt = "1.22.0"
spotless = "6.11.0"
google-services = "4.3.10"
play-services-ads = "20.5.0"
play-services-base = "18.0.1"
firebase-analytics = "21.1.1"
firebase-appdistribution = "3.0.3"
firebase-config = "21.1.2"
firebase-crashlytics-plugin = "2.9.2"
firebase-crashlytics = "18.2.13"
play-core = "1.8.1"
accompanist = "0.27.1"
compose-foundation = "1.3.1"
compose-runtime = "1.3.1"
compose-ui = "1.3.1"
compose-compiler = "1.3.2"
compose-material3 = "1.0.1"
material = "1.6.0"
material-compose-theme-adapter = "1.1.3"
appcompat = "1.6.0-rc01"
activity = "1.6.1"
core = "1.8.0"
core-splashscreen = "1.0.0"
constraintlayout = "1.0.1"
lifecycle = "2.6.0-alpha03"
hilt = "2.44"
hilt-navigation-compose = "1.0.0"
navigation = "2.5.3"
paging = "1.0.0-alpha16"
datastore = "1.0.0"
startup = "1.1.1"
coil = "2.2.1"
okhttp = "4.10.0"
retrofit = "2.9.0"
retrofit-converter-serialization = "0.8.0"
chucker = "3.5.2"
timber = "5.0.1"
javapoet = "1.13.0"
room = "2.4.3"

[libraries]
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "play-services-ads" }
play-services-base = { group = "com.google.android.gms", name = "play-services-base", version.ref = "play-services-base" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebase-analytics" }
firebase-config = { group = "com.google.firebase", name = "firebase-config-ktx", version.ref = "firebase-config" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebase-crashlytics" }
play-core = { group = "com.google.android.play", name = "core-ktx", version.ref = "play-core" }
accompanist-appcompat-theme = { group = "com.google.accompanist", name = "accompanist-appcompat-theme", version.ref = "accompanist" }
accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-insets = { group = "com.google.accompanist", name = "accompanist-insets", version.ref = "accompanist" }
accompanist-insets-ui = { group = "com.google.accompanist", name = "accompanist-insets-ui", version.ref = "accompanist" }
accompanist-navigation-animation = { group = "com.google.accompanist", name = "accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "compose-compiler" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose-foundation" }
compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "compose-foundation" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose-runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
compose-ui-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding", version.ref = "compose-ui" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-compose-theme-adapter = { group = "com.google.android.material", name = "compose-theme-adapter", version.ref = "material-compose-theme-adapter" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
appcompat-resources = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "appcompat" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "datastore" }
startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-converter-serialization" }
chucker-library = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
chucker-library-no-op = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chucker" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }

gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
kotlin-coroutines = ["kotlin-coroutines-core", "kotlin-coroutines-android"]
accompanist = ["accompanist-appcompat-theme", "accompanist-drawablepainter", "accompanist-insets", "accompanist-insets-ui", "accompanist-navigation-animation", "accompanist-systemuicontroller"]
appcompat = ["appcompat", "appcompat-resources"]
compose = ["compose-compiler", "compose-foundation", "compose-foundation-layout", "compose-material3", "compose-runtime", "compose-ui", "compose-ui-tooling", "compose-ui-viewbinding"]
datastore = ["datastore-core", "datastore-preferences", "datastore-preferences-core"]
lifecycle = ["lifecycle-runtime-compose", "lifecycle-viewmodel-compose"]
material = ["material", "material-compose-theme-adapter"]

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebase-appdistribution" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }